# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gradients_demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod "Gradients"
  # Pods for Gradients_demo

  target 'Gradients_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Gradients_demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
